---
development:
  dialect: postgres
  database: robust_code
  user: root
  password: postgres
  host: 127.0.0.1
  port: 55444     # ← tambahkan ini
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/robust_code_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/robust_code_production?sslmode=disable"}}
